// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJxadOSQuQOo0h1fuJNlRKkSTal7mwXLM',
    appId: '1:886390512554:web:f7dcd18a97f3d79a4d69d3',
    messagingSenderId: '886390512554',
    projectId: 'swapar-69706',
    authDomain: 'swapar-69706.firebaseapp.com',
    storageBucket: 'swapar-69706.firebasestorage.app',
    measurementId: 'G-YXZL2J5D04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHuSnndvG4Er4iyTPN-6kcqRCTEg15kU',
    appId: '1:886390512554:android:e10a08fadc9db86e4d69d3',
    messagingSenderId: '886390512554',
    projectId: 'swapar-69706',
    storageBucket: 'swapar-69706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPpAZtNsSZaNJl2jSpolHsG4-Xf4T0BM',
    appId: '1:886390512554:ios:32597a7965d8d09f4d69d3',
    messagingSenderId: '886390512554',
    projectId: 'swapar-69706',
    storageBucket: 'swapar-69706.firebasestorage.app',
    iosBundleId: 'com.example.swipar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQPpAZtNsSZaNJl2jSpolHsG4-Xf4T0BM',
    appId: '1:886390512554:ios:32597a7965d8d09f4d69d3',
    messagingSenderId: '886390512554',
    projectId: 'swapar-69706',
    storageBucket: 'swapar-69706.firebasestorage.app',
    iosBundleId: 'com.example.swipar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJxadOSQuQOo0h1fuJNlRKkSTal7mwXLM',
    appId: '1:886390512554:web:2d145ab13f3044504d69d3',
    messagingSenderId: '886390512554',
    projectId: 'swapar-69706',
    authDomain: 'swapar-69706.firebaseapp.com',
    storageBucket: 'swapar-69706.firebasestorage.app',
    measurementId: 'G-K2WQLHXN5F',
  );
}
